### PR TITLE
fix load cli bug in Windows(https://github.com/wakatime/texstudio-wakatime/issues/1)

### PR DESCRIPTION
**Pull request by callanwu**

### CODE REVIEW

**Comment by callanwu** [comment]
@alanhamlett i am not familiar with js file lol, so i replace cli in the **args** array using python.

**Comment by callanwu** [comment]
it works in my computer which is a Windows platform

**Comment by callanwu** [comment]
@alanhamlett PTAL

**Review by alanhamlett — CHANGES_REQUESTED** [review]
We shouldn't modify the JS source code here, its only for copying the JS files to the install folder.

**Comment by callanwu** [comment]
yeah, but it doesn't work on Windows platform, it need to change the wakatime path like https://github.com/wakatime/texstudio-wakatime/issues/1#issuecomment-1264999298. i change it in the args array using python.

**Comment by alanhamlett** [comment]
Fixed in v2.0.2.

**Comment by callanwu** [comment]
great

**Pull request closed without merging**
