### PR TITLE
Fix #5.

### LINKED ISSUE #5: TypeError: Object of type bytes is not JSON serializable
When trying to execute `install.py`, I'm getting the following error in line 108.

```
TypeError: Object of type bytes is not JSON serializable
```

### PR DESCRIPTION
**Pull request by muety**

### CODE REVIEW

**Comment by alanhamlett** [comment]
We need to make this change support both Python2 and Python3, by checking `PY2` variable or using `try/except`:
https://github.com/wakatime/texstudio-wakatime/blob/bf1e4200570f85b5e7a8aa1e1469ef42b06927e6/install.py#L34

**Comment by muety** [comment]
The change was successfully tested with both Python 2.7 and 3.7.

**Comment by muety** [comment]
Are you ok with my changes?

**Comment by alanhamlett** [comment]
I think with Python2 this will incorrectly double-decode the string. Let's merge it and I'll test further on master.

**Pull request merged**
